 module.exports.cities = ["ALTAMONTE SPRINGS", "APOPKA", "CASSELBERRY", "LONGWOOD", "MAITLAND", "ORLANDO",
            "WINTER PARK", "WINTER SPRINGS", "KISSIMMEE", "HUNTERS CREEK", "DR PHILLIPS", "WEDGEWOOD",
            "MOSS PARK", "BAY HILL", "BALDWIN", "WINDERMERE", "GOTHA", "OCOEE", "WINTER GARDEN",
            "HAINES CITY"];
